services:
  App\Domain\Messages\Handler\User\CreateUserMessageHandler:
    public: true
    arguments:
      - '@App\Infrastructure\MongoDB\Repository\UserRepository'
      - '@event_dispatcher'
    tags:
      - messenger.message_handler
      - messenger.bus.commands