services:
  App\Infrastructure\Validator\Constraints\CreateUserValidator:
    arguments:
      - '@App\Infrastructure\MongoDB\Repository\UserRepository'
    tags:
      - 'validator.constraint_validator'