---
- name: Add Required Packages
  apt:
    pkg:
      - ca-certificates
      - apt-transport-https

- name: Add PHP Repo Key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg

- name: Add PHP Repo
  apt_repository:
    repo: 'deb https://packages.sury.org/php/ stretch main'

- name: Install PHP-FPM
  apt:
    pkg:
      - php7.3-fpm
      - php7.3-common
      - php7.3-iconv
      - php7.3-json
      - php7.3-xml
      - php7.3-tokenizer
      - php7.3-curl
      - php7.3-mbstring
      - php7.3-zip
      - php7.3-amqp
      - php7.3-mongodb
    state: latest

- name: Configure PHP-FPM pool
  template:
    src: www.conf.j2
    dest: /etc/php/7.3/fpm/pool.d/www.conf
    owner: root
    group: root

- name: Set PHP-FPM Socket Permission
  notify:
    - Start PHP
  file:
    dest: /var/run/php
    owner: "{{ php_fpm_user }}"
    group: "{{ php_fpm_group }}"
    recurse: yes

- name: Download composer
  become: vagrant
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php

- name: Install composer
  command: "{{ item }}"
  with_items:
    - "php /tmp/composer-installer.php"
    - mv composer.phar /usr/local/bin/composer

- name: Cleanup
  file:
    path: /tmp/composer-installer.php
    state: absent

- name: Install Composer Packages
  become: vagrant
  composer:
    command: install
    working_dir: "{{ nginx_folder }}"

- name: Generate JWT private key
  openssl_privatekey:
    path: "{{ nginx_folder }}/config/jwt/private.pem"

- name: Generate JWT public key
  openssl_publickey:
    path: "{{ nginx_folder }}/config/jwt/public.pem"
    privatekey_path: "{{ nginx_folder }}/config/jwt/private.pem"