doctrine_mongodb:
  auto_generate_proxy_classes: true
  auto_generate_hydrator_classes: true
  connections:
    default:
      server: '%env(MONGODB_URL)%'
      options: {}
  default_database: '%env(MONGODB_DB)%'
  document_managers:
    default:
      mappings:
        App:
          is_bundle: false
          type: yml
          dir: '%kernel.project_dir%/config/mongodb/mappings'
          prefix: 'App\Domain\Model'
          alias: App