---
- name: Add Mongo Repo Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4
    state: present

- name: Add Mongo Repo
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 main

- name: Install MongoDB
  notify: Start Mongo
  apt:
    pkg:
      - mongodb-org