App\Domain\Model\User:
  type: document
  collection: users
  fields:
    id:
      id: true
      strategy: NONE
      type: string
    username:
      type: string
    email:
      type: string
    password:
      type: string
    roles:
      type: UserRole