version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../src:/var/www
  nxing:
    build:
      context: ./nginx
    volumes:
      - ../backend :/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
  database:
    build:
      context: ./database
    env_file:
      - ./.env
    ports:
      - "3307:3306"