---
- name: Add System Packages
  apt:
    pkg:
      - htop
      - git
      - unzip
    state: latest

- name: Add Python Package Manager
  easy_install:
    name: pip
    state: latest

- name: Add Required Python Packages
  pip:
    name: pyOpenSSL